/* =============================================
   data.js - 게임 콘텐츠 데이터 (확장판)
   단어, 문장, 퀴즈 문제 모음
   난이도별 (beginner / intermediate / advanced)
   ============================================= */

const GameData = {

  words: {
    beginner: [
      // 인사 (10)
      { kr: "안녕하세요",    romanization: "annyeonghaseyo",    en: "Hello",                          category: "greetings" },
      { kr: "안녕히 가세요", romanization: "annyeonghi gaseyo", en: "Goodbye (to one leaving)",        category: "greetings" },
      { kr: "안녕히 계세요", romanization: "annyeonghi gyeseyo",en: "Goodbye (to one staying)",        category: "greetings" },
      { kr: "감사합니다",    romanization: "gamsahamnida",      en: "Thank you",                      category: "greetings" },
      { kr: "미안합니다",    romanization: "mianhamnida",       en: "I am sorry",                     category: "greetings" },
      { kr: "괜찮아요",     romanization: "gwaenchanayo",      en: "It is okay / Are you okay?",      category: "greetings" },
      { kr: "네",          romanization: "ne",                en: "Yes",                            category: "greetings" },
      { kr: "아니요",      romanization: "aniyo",             en: "No",                             category: "greetings" },
      { kr: "이름",        romanization: "ireum",             en: "Name",                           category: "greetings" },
      { kr: "반갑습니다",   romanization: "bangapseumnida",    en: "Nice to meet you",               category: "greetings" },
      // 음식 (14)
      { kr: "물",          romanization: "mul",               en: "Water",                          category: "food" },
      { kr: "밥",          romanization: "bap",               en: "Rice / Meal",                    category: "food" },
      { kr: "빵",          romanization: "ppang",             en: "Bread",                          category: "food" },
      { kr: "우유",        romanization: "uyu",               en: "Milk",                           category: "food" },
      { kr: "사과",        romanization: "sagwa",             en: "Apple",                          category: "food" },
      { kr: "바나나",      romanization: "banana",            en: "Banana",                         category: "food" },
      { kr: "고기",        romanization: "gogi",              en: "Meat",                           category: "food" },
      { kr: "계란",        romanization: "gyeran",            en: "Egg",                            category: "food" },
      { kr: "커피",        romanization: "keopi",             en: "Coffee",                         category: "food" },
      { kr: "차",          romanization: "cha",               en: "Tea",                            category: "food" },
      { kr: "주스",        romanization: "juseu",             en: "Juice",                          category: "food" },
      { kr: "국",          romanization: "guk",               en: "Soup",                           category: "food" },
      { kr: "김치",        romanization: "kimchi",            en: "Kimchi",                         category: "food" },
      { kr: "라면",        romanization: "ramyeon",           en: "Ramen / Instant noodles",        category: "food" },
      // 숫자 (10)
      { kr: "하나",        romanization: "hana",              en: "One",                            category: "numbers" },
      { kr: "둘",          romanization: "dul",               en: "Two",                            category: "numbers" },
      { kr: "셋",          romanization: "set",               en: "Three",                          category: "numbers" },
      { kr: "넷",          romanization: "net",               en: "Four",                           category: "numbers" },
      { kr: "다섯",        romanization: "daseot",            en: "Five",                           category: "numbers" },
      { kr: "여섯",        romanization: "yeoseot",           en: "Six",                            category: "numbers" },
      { kr: "일곱",        romanization: "ilgop",             en: "Seven",                          category: "numbers" },
      { kr: "여덟",        romanization: "yeodeol",           en: "Eight",                          category: "numbers" },
      { kr: "아홉",        romanization: "ahop",              en: "Nine",                           category: "numbers" },
      { kr: "열",          romanization: "yeol",              en: "Ten",                            category: "numbers" },
      // 색깔 (6)
      { kr: "빨간색",      romanization: "ppalgansaek",       en: "Red",                            category: "colors" },
      { kr: "파란색",      romanization: "paransaek",         en: "Blue",                           category: "colors" },
      { kr: "노란색",      romanization: "noransaek",         en: "Yellow",                         category: "colors" },
      { kr: "초록색",      romanization: "choroksaek",        en: "Green",                          category: "colors" },
      { kr: "하얀색",      romanization: "hayansaek",         en: "White",                          category: "colors" },
      { kr: "검은색",      romanization: "geomeunsaek",       en: "Black",                          category: "colors" },
      // 가족 (8)
      { kr: "어머니",      romanization: "eomeoni",           en: "Mother",                         category: "family" },
      { kr: "아버지",      romanization: "abeoji",            en: "Father",                         category: "family" },
      { kr: "형",          romanization: "hyeong",            en: "Older brother (said by boy)",    category: "family" },
      { kr: "누나",        romanization: "nuna",              en: "Older sister (said by boy)",     category: "family" },
      { kr: "언니",        romanization: "eonni",             en: "Older sister (said by girl)",    category: "family" },
      { kr: "오빠",        romanization: "oppa",              en: "Older brother (said by girl)",   category: "family" },
      { kr: "동생",        romanization: "dongsaeng",         en: "Younger sibling",                category: "family" },
      { kr: "할머니",      romanization: "halmeoni",          en: "Grandmother",                    category: "family" },
      // 신체 (10)
      { kr: "눈",          romanization: "nun",               en: "Eye(s)",                         category: "body" },
      { kr: "코",          romanization: "ko",                en: "Nose",                           category: "body" },
      { kr: "입",          romanization: "ip",                en: "Mouth",                          category: "body" },
      { kr: "귀",          romanization: "gwi",               en: "Ear",                            category: "body" },
      { kr: "손",          romanization: "son",               en: "Hand",                           category: "body" },
      { kr: "발",          romanization: "bal",               en: "Foot",                           category: "body" },
      { kr: "머리",        romanization: "meori",             en: "Head / Hair",                    category: "body" },
      { kr: "배",          romanization: "bae",               en: "Stomach / Belly",                category: "body" },
      { kr: "다리",        romanization: "dari",              en: "Leg",                            category: "body" },
      { kr: "목",          romanization: "mok",               en: "Neck / Throat",                  category: "body" },
      // 동물 (8)
      { kr: "개",          romanization: "gae",               en: "Dog",                            category: "animals" },
      { kr: "고양이",      romanization: "goyangi",           en: "Cat",                            category: "animals" },
      { kr: "새",          romanization: "sae",               en: "Bird",                           category: "animals" },
      { kr: "토끼",        romanization: "tokki",             en: "Rabbit",                         category: "animals" },
      { kr: "소",          romanization: "so",                en: "Cow",                            category: "animals" },
      { kr: "돼지",        romanization: "dwaeji",            en: "Pig",                            category: "animals" },
      { kr: "닭",          romanization: "dak",               en: "Chicken",                        category: "animals" },
      { kr: "물고기",      romanization: "mulgogi",           en: "Fish",                           category: "animals" },
      // 옷 (8)
      { kr: "옷",          romanization: "ot",                en: "Clothes",                        category: "clothes" },
      { kr: "바지",        romanization: "baji",              en: "Pants / Trousers",               category: "clothes" },
      { kr: "치마",        romanization: "chima",             en: "Skirt",                          category: "clothes" },
      { kr: "신발",        romanization: "sinbal",            en: "Shoes",                          category: "clothes" },
      { kr: "모자",        romanization: "moja",              en: "Hat / Cap",                      category: "clothes" },
      { kr: "셔츠",        romanization: "syeocheu",          en: "Shirt",                          category: "clothes" },
      { kr: "양말",        romanization: "yangmal",           en: "Socks",                          category: "clothes" },
      { kr: "코트",        romanization: "koteu",             en: "Coat",                           category: "clothes" },
      // 요일 (7)
      { kr: "월요일",      romanization: "woryoil",           en: "Monday",                         category: "days" },
      { kr: "화요일",      romanization: "hwayoil",           en: "Tuesday",                        category: "days" },
      { kr: "수요일",      romanization: "suyoil",            en: "Wednesday",                      category: "days" },
      { kr: "목요일",      romanization: "mogyoil",           en: "Thursday",                       category: "days" },
      { kr: "금요일",      romanization: "geumyoil",          en: "Friday",                         category: "days" },
      { kr: "토요일",      romanization: "toyoil",            en: "Saturday",                       category: "days" },
      { kr: "일요일",      romanization: "iryoil",            en: "Sunday",                         category: "days" },
      // 일상 (9)
      { kr: "사람",        romanization: "saram",             en: "Person",                         category: "daily" },
      { kr: "집",          romanization: "jip",               en: "House / Home",                   category: "daily" },
      { kr: "학교",        romanization: "hakgyo",            en: "School",                         category: "daily" },
      { kr: "친구",        romanization: "chingu",            en: "Friend",                         category: "daily" },
      { kr: "가방",        romanization: "gabang",            en: "Bag",                            category: "daily" },
      { kr: "책",          romanization: "chaek",             en: "Book",                           category: "daily" },
      { kr: "의자",        romanization: "uija",              en: "Chair",                          category: "daily" },
      { kr: "시간",        romanization: "sigan",             en: "Time",                           category: "daily" },
      { kr: "선생님",      romanization: "seonsaengnim",      en: "Teacher",                        category: "daily" }
    ],
    intermediate: [
      // 음식 (14)
      { kr: "비빔밥",      romanization: "bibimbap",          en: "Mixed rice bowl",               category: "food" },
      { kr: "삼겹살",      romanization: "samgyeopsal",       en: "Grilled pork belly",            category: "food" },
      { kr: "김치찌개",    romanization: "kimchijjigae",      en: "Kimchi stew",                   category: "food" },
      { kr: "떡볶이",      romanization: "tteokbokki",        en: "Spicy rice cakes",              category: "food" },
      { kr: "순두부찌개",  romanization: "sundubu jjigae",    en: "Soft tofu stew",                category: "food" },
      { kr: "냉면",        romanization: "naengmyeon",        en: "Cold noodles",                  category: "food" },
      { kr: "잡채",        romanization: "japchae",           en: "Glass noodle stir-fry",         category: "food" },
      { kr: "불고기",      romanization: "bulgogi",           en: "Marinated grilled beef",        category: "food" },
      { kr: "파전",        romanization: "pajeon",            en: "Green onion pancake",           category: "food" },
      { kr: "삼계탕",      romanization: "samgyetang",        en: "Ginseng chicken soup",          category: "food" },
      { kr: "갈비",        romanization: "galbi",             en: "Ribs (grilled)",                category: "food" },
      { kr: "된장찌개",    romanization: "doenjang jjigae",   en: "Fermented soybean paste stew",  category: "food" },
      { kr: "칼국수",      romanization: "kalguksu",          en: "Knife-cut noodle soup",         category: "food" },
      { kr: "떡국",        romanization: "tteokguk",          en: "Rice cake soup",                category: "food" },
      // 여행 (12)
      { kr: "지하철",      romanization: "jihacheol",         en: "Subway / Metro",                category: "travel" },
      { kr: "버스",        romanization: "beoseu",            en: "Bus",                           category: "travel" },
      { kr: "공항",        romanization: "gonghang",          en: "Airport",                       category: "travel" },
      { kr: "호텔",        romanization: "hotel",             en: "Hotel",                         category: "travel" },
      { kr: "얼마예요?",   romanization: "eolmayeyo?",        en: "How much is it?",               category: "travel" },
      { kr: "어디예요?",   romanization: "eodiyeyo?",         en: "Where is it?",                  category: "travel" },
      { kr: "표",          romanization: "pyo",               en: "Ticket",                        category: "travel" },
      { kr: "여권",        romanization: "yeogwon",           en: "Passport",                      category: "travel" },
      { kr: "환전",        romanization: "hwanjeon",          en: "Currency exchange",             category: "travel" },
      { kr: "화장실",      romanization: "hwajangsil",        en: "Restroom / Bathroom",           category: "travel" },
      { kr: "기차",        romanization: "gicha",             en: "Train",                         category: "travel" },
      { kr: "택시",        romanization: "taeksi",            en: "Taxi",                          category: "travel" },
      // K-pop / 문화 (10)
      { kr: "대박",        romanization: "daebak",            en: "Awesome / Jackpot",             category: "kpop" },
      { kr: "화이팅",      romanization: "hwaiting",          en: "Fighting! / Go for it!",        category: "kpop" },
      { kr: "아이돌",      romanization: "aidol",             en: "Idol",                          category: "kpop" },
      { kr: "보고 싶어",   romanization: "bogo sipeo",        en: "I miss you",                    category: "kpop" },
      { kr: "팬",          romanization: "paen",              en: "Fan",                           category: "kpop" },
      { kr: "콘서트",      romanization: "konseuteu",         en: "Concert",                       category: "kpop" },
      { kr: "노래",        romanization: "norae",             en: "Song",                          category: "kpop" },
      { kr: "앨범",        romanization: "aelbum",            en: "Album",                         category: "kpop" },
      { kr: "팬덤",        romanization: "paendeom",          en: "Fandom",                        category: "kpop" },
      { kr: "뮤직비디오",  romanization: "myujik bidio",      en: "Music video",                   category: "kpop" },
      // 직업 (10)
      { kr: "의사",        romanization: "uisa",              en: "Doctor",                        category: "jobs" },
      { kr: "약사",        romanization: "yaksa",             en: "Pharmacist",                    category: "jobs" },
      { kr: "요리사",      romanization: "yorisa",            en: "Chef / Cook",                   category: "jobs" },
      { kr: "경찰관",      romanization: "gyeongchalgwan",    en: "Police officer",                category: "jobs" },
      { kr: "배우",        romanization: "baeu",              en: "Actor / Actress",               category: "jobs" },
      { kr: "가수",        romanization: "gasu",              en: "Singer",                        category: "jobs" },
      { kr: "작가",        romanization: "jakga",             en: "Writer / Author",               category: "jobs" },
      { kr: "운전기사",    romanization: "unjeon gisa",       en: "Driver",                        category: "jobs" },
      { kr: "간호사",      romanization: "ganhosa",           en: "Nurse",                         category: "jobs" },
      { kr: "회사원",      romanization: "hoesawon",          en: "Office worker",                 category: "jobs" },
      // 취미 (10)
      { kr: "독서",        romanization: "dokseo",            en: "Reading (books)",               category: "hobbies" },
      { kr: "운동",        romanization: "undong",            en: "Exercise / Sports",             category: "hobbies" },
      { kr: "요리",        romanization: "yori",              en: "Cooking",                       category: "hobbies" },
      { kr: "그림",        romanization: "geurim",            en: "Drawing / Painting",            category: "hobbies" },
      { kr: "음악",        romanization: "eumak",             en: "Music",                         category: "hobbies" },
      { kr: "여행",        romanization: "yeohaeng",          en: "Travel",                        category: "hobbies" },
      { kr: "게임",        romanization: "geim",              en: "Gaming",                        category: "hobbies" },
      { kr: "수영",        romanization: "suyeong",           en: "Swimming",                      category: "hobbies" },
      { kr: "등산",        romanization: "deungsan",          en: "Hiking",                        category: "hobbies" },
      { kr: "춤",          romanization: "chum",              en: "Dance",                         category: "hobbies" },
      // 쇼핑 (8)
      { kr: "가격",        romanization: "gagyeok",           en: "Price",                         category: "shopping" },
      { kr: "할인",        romanization: "halin",             en: "Discount",                      category: "shopping" },
      { kr: "영수증",      romanization: "yeongsujeung",      en: "Receipt",                       category: "shopping" },
      { kr: "카드",        romanization: "kadeu",             en: "Card (payment)",                category: "shopping" },
      { kr: "사이즈",      romanization: "saiseu",            en: "Size",                          category: "shopping" },
      { kr: "교환",        romanization: "gyohwan",           en: "Exchange",                      category: "shopping" },
      { kr: "환불",        romanization: "hwanbul",           en: "Refund",                        category: "shopping" },
      { kr: "세일",        romanization: "seil",              en: "Sale",                          category: "shopping" },
      // 감정 (8)
      { kr: "행복하다",    romanization: "haengbokhada",      en: "To be happy",                   category: "feelings" },
      { kr: "슬프다",      romanization: "seulpeuda",         en: "To be sad",                     category: "feelings" },
      { kr: "화가 나다",   romanization: "hwaga nada",        en: "To be angry",                   category: "feelings" },
      { kr: "피곤하다",    romanization: "pigonhada",         en: "To be tired",                   category: "feelings" },
      { kr: "배고프다",    romanization: "baegoppeuda",       en: "To be hungry",                  category: "feelings" },
      { kr: "기쁘다",      romanization: "gippeuda",          en: "To be glad / joyful",           category: "feelings" },
      { kr: "걱정되다",    romanization: "geokjeongdoeda",    en: "To be worried",                 category: "feelings" },
      { kr: "긴장되다",    romanization: "ginjanddoeda",      en: "To be nervous",                 category: "feelings" },
      // 건강 (8)
      { kr: "아프다",      romanization: "apeuda",            en: "To be sick / hurt",             category: "health" },
      { kr: "감기",        romanization: "gamgi",             en: "Cold / Flu",                    category: "health" },
      { kr: "두통",        romanization: "dutong",            en: "Headache",                      category: "health" },
      { kr: "열",          romanization: "yeol",              en: "Fever",                         category: "health" },
      { kr: "약",          romanization: "yak",               en: "Medicine",                      category: "health" },
      { kr: "주사",        romanization: "jusa",              en: "Injection / Shot",              category: "health" },
      { kr: "건강",        romanization: "geongang",          en: "Health",                        category: "health" },
      { kr: "다이어트",    romanization: "daieoteu",          en: "Diet",                          category: "health" },
      // 자연/날씨 (10)
      { kr: "비",          romanization: "bi",                en: "Rain",                          category: "nature" },
      { kr: "눈(snow)",    romanization: "nun",               en: "Snow",                          category: "nature" },
      { kr: "바람",        romanization: "baram",             en: "Wind",                          category: "nature" },
      { kr: "구름",        romanization: "gureum",            en: "Cloud",                         category: "nature" },
      { kr: "태양",        romanization: "taeyang",           en: "Sun",                           category: "nature" },
      { kr: "하늘",        romanization: "haneul",            en: "Sky",                           category: "nature" },
      { kr: "산",          romanization: "san",               en: "Mountain",                      category: "nature" },
      { kr: "바다",        romanization: "bada",              en: "Sea / Ocean",                   category: "nature" },
      { kr: "강",          romanization: "gang",              en: "River",                         category: "nature" },
      { kr: "꽃",          romanization: "kkot",              en: "Flower",                        category: "nature" }
    ],
    advanced: [
      // 문화 개념 (12)
      { kr: "눈치",          romanization: "nunchi",           en: "Social awareness / reading the room",   category: "culture" },
      { kr: "정",            romanization: "jeong",            en: "Deep emotional bond / attachment",      category: "culture" },
      { kr: "빨리빨리",      romanization: "ppalli ppalli",    en: "Hurry hurry / speed culture",           category: "culture" },
      { kr: "한",            romanization: "han",              en: "Deep-seated sorrow / collective grief", category: "culture" },
      { kr: "체면",          romanization: "chemyeon",         en: "Social face / dignity",                 category: "culture" },
      { kr: "갑",            romanization: "gap",              en: "Party A / person in power",             category: "culture" },
      { kr: "을",            romanization: "eul",              en: "Party B / person of lower status",     category: "culture" },
      { kr: "눈치채다",      romanization: "nunchichaeda",     en: "To sense / pick up on something",      category: "culture" },
      { kr: "분위기",        romanization: "bunuigi",          en: "Atmosphere / vibe",                     category: "culture" },
      { kr: "여유",          romanization: "yeoyu",            en: "Leisure / ease / breathing room",       category: "culture" },
      { kr: "배려",          romanization: "baeryeo",          en: "Consideration / care for others",       category: "culture" },
      { kr: "흥",            romanization: "heung",            en: "Excitement / joy / high spirits",       category: "culture" },
      // 표현 (12)
      { kr: "어쩔 수 없다",  romanization: "eojjeol su eopda", en: "There is no other way",                category: "expressions" },
      { kr: "그러게요",      romanization: "geureogeyo",       en: "I know right / Exactly",               category: "expressions" },
      { kr: "아무튼",        romanization: "amutun",           en: "Anyway / In any case",                 category: "expressions" },
      { kr: "솔직히",        romanization: "soljikhi",         en: "Honestly / To be frank",               category: "expressions" },
      { kr: "귀찮다",        romanization: "gwichanta",        en: "It is a hassle / Can not be bothered",  category: "expressions" },
      { kr: "설레다",        romanization: "seolleda",         en: "Excited anticipation / flutter",        category: "expressions" },
      { kr: "어색하다",      romanization: "eosaekada",        en: "To feel awkward",                      category: "expressions" },
      { kr: "고생했어",      romanization: "gosaenghaesseo",   en: "You worked hard (acknowledgment)",     category: "expressions" },
      { kr: "밥 먹었어?",    romanization: "bap meogeosseo?",  en: "Did you eat? (casual greeting)",       category: "expressions" },
      { kr: "뿌듯하다",      romanization: "ppudeutada",       en: "Feeling of proud satisfaction",        category: "expressions" },
      { kr: "서운하다",      romanization: "seounnada",        en: "Feeling hurt / left out",              category: "expressions" },
      { kr: "억울하다",      romanization: "eogulhada",        en: "Feeling wronged / treated unfairly",   category: "expressions" },
      // 문법 (10)
      { kr: "존댓말",        romanization: "jondaemal",        en: "Formal / polite speech level",         category: "grammar" },
      { kr: "반말",          romanization: "banmal",           en: "Informal / casual speech",             category: "grammar" },
      { kr: "조사",          romanization: "josa",             en: "Particle (grammar)",                   category: "grammar" },
      { kr: "이/가",         romanization: "i/ga",             en: "Subject particle",                     category: "grammar" },
      { kr: "을/를",         romanization: "eul/reul",         en: "Object particle",                      category: "grammar" },
      { kr: "에서",          romanization: "eseo",             en: "At / In (location of action)",         category: "grammar" },
      { kr: "은/는",         romanization: "eun/neun",         en: "Topic particle",                       category: "grammar" },
      { kr: "에게",          romanization: "ege",              en: "To (person) / for (person)",           category: "grammar" },
      { kr: "와/과",         romanization: "wa/gwa",           en: "And / With (connecting nouns)",        category: "grammar" },
      { kr: "높임말",        romanization: "nopimmal",         en: "Honorific language",                   category: "grammar" },
      // K-drama / 엔터 (10)
      { kr: "드라마",        romanization: "deurama",          en: "Drama (TV show)",                      category: "drama" },
      { kr: "주인공",        romanization: "juingong",         en: "Main character / Protagonist",         category: "drama" },
      { kr: "사랑해",        romanization: "saranghae",        en: "I love you (casual)",                  category: "drama" },
      { kr: "운명",          romanization: "unmyeong",         en: "Fate / Destiny",                       category: "drama" },
      { kr: "짝사랑",        romanization: "jjaksarang",       en: "One-sided / unrequited love",          category: "drama" },
      { kr: "남주",          romanization: "namju",            en: "Male lead (drama slang)",              category: "drama" },
      { kr: "여주",          romanization: "yeoju",            en: "Female lead (drama slang)",            category: "drama" },
      { kr: "한류",          romanization: "hallyu",           en: "Korean Wave",                          category: "drama" },
      { kr: "안무",          romanization: "anmu",             en: "Choreography",                         category: "drama" },
      { kr: "오디션",        romanization: "odisyeon",         en: "Audition",                             category: "drama" },
      // 사자성어 (8)
      { kr: "일석이조",      romanization: "ilseogijo",        en: "Kill two birds with one stone",        category: "idioms" },
      { kr: "이심전심",      romanization: "isimjeonsim",      en: "Heart to heart / mutual understanding", category: "idioms" },
      { kr: "고진감래",      romanization: "gojingamrae",      en: "After hardship comes happiness",       category: "idioms" },
      { kr: "새옹지마",      romanization: "saeongjima",       en: "Every cloud has a silver lining",      category: "idioms" },
      { kr: "작심삼일",      romanization: "jaksimsamil",      en: "Resolution that lasts only three days", category: "idioms" },
      { kr: "금상첨화",      romanization: "geumsangcheomhwa", en: "Adding flowers to brocade / even better", category: "idioms" },
      { kr: "동병상련",      romanization: "dongbyeongsangnyeon", en: "Sharing the same sorrow / empathy", category: "idioms" },
      { kr: "오매불망",      romanization: "omaeblmang",       en: "Can not stop thinking about someone",  category: "idioms" },
      // 비즈니스 (8)
      { kr: "회의",          romanization: "hoeui",            en: "Meeting",                              category: "business" },
      { kr: "발표",          romanization: "balpyo",           en: "Presentation / Announcement",          category: "business" },
      { kr: "계약",          romanization: "gyeyak",           en: "Contract",                             category: "business" },
      { kr: "협상",          romanization: "hyeopssang",       en: "Negotiation",                          category: "business" },
      { kr: "보고서",        romanization: "bogoseo",          en: "Report",                               category: "business" },
      { kr: "마감",          romanization: "magam",            en: "Deadline",                             category: "business" },
      { kr: "출장",          romanization: "chuljang",         en: "Business trip",                        category: "business" },
      { kr: "회사",          romanization: "hoesa",            en: "Company",                              category: "business" },
      // 역사/문화2 (10)
      { kr: "세종대왕",      romanization: "Sejong Daewang",   en: "King Sejong the Great",                category: "history" },
      { kr: "조선",          romanization: "Joseon",           en: "Joseon Dynasty",                       category: "history" },
      { kr: "태권도",        romanization: "taekwondo",        en: "Taekwondo",                            category: "history" },
      { kr: "한옥",          romanization: "hanok",            en: "Traditional Korean house",             category: "history" },
      { kr: "한복",          romanization: "hanbok",           en: "Traditional Korean clothing",          category: "history" },
      { kr: "고려",          romanization: "Goryeo",           en: "Goryeo Dynasty",                       category: "history" },
      { kr: "신뢰",          romanization: "sinroe",           en: "Trust",                                category: "history" },
      { kr: "용기",          romanization: "yonggi",           en: "Courage",                              category: "history" },
      { kr: "지혜",          romanization: "jihye",            en: "Wisdom",                               category: "history" },
      { kr: "겸손",          romanization: "gyeomson",         en: "Humility",                             category: "history" }
    ]
  },
  fillBlank: {
    beginner: [
      { sentence_en: "Hello, nice to meet you.",        sentence_kr: "___, 만나서 반갑습니다.",           blank: "___", options: ["안녕하세요","감사합니다","미안합니다","잘 가요"],          answer: "안녕하세요" },
      { sentence_en: "I want to drink water.",          sentence_kr: "저는 ___을 마시고 싶어요.",         blank: "___", options: ["밥","물","우유","빵"],                         answer: "물" },
      { sentence_en: "This person is my friend.",       sentence_kr: "이 사람은 제 ___이에요.",           blank: "___", options: ["가족","선생님","친구","학생"],                   answer: "친구" },
      { sentence_en: "I go to school every day.",       sentence_kr: "저는 매일 ___에 가요.",             blank: "___", options: ["집","학교","병원","시장"],                      answer: "학교" },
      { sentence_en: "Thank you very much!",            sentence_kr: "정말 ___!",                         blank: "___", options: ["미안합니다","안녕하세요","감사합니다","잘 자요"],  answer: "감사합니다" },
      { sentence_en: "The apple is red.",               sentence_kr: "___는 빨간색이에요.",               blank: "___", options: ["바나나","우유","사과","물"],                     answer: "사과" },
      { sentence_en: "My mother is very kind.",         sentence_kr: "제 ___는 정말 친절해요.",           blank: "___", options: ["아버지","어머니","동생","친구"],                 answer: "어머니" },
      { sentence_en: "I have a book in my bag.",        sentence_kr: "___에 책이 있어요.",                blank: "___", options: ["의자","가방","집","학교"],                      answer: "가방" },
      { sentence_en: "I am sorry, it was my mistake.",  sentence_kr: "___, 제 실수였어요.",               blank: "___", options: ["감사합니다","안녕하세요","괜찮아요","미안합니다"], answer: "미안합니다" },
      { sentence_en: "My younger sibling is cute.",     sentence_kr: "제 ___는 귀여워요.",                blank: "___", options: ["어머니","아버지","동생","친구"],                 answer: "동생" },
      { sentence_en: "What is your name?",              sentence_kr: "___이 뭐예요?",                     blank: "___", options: ["나이","이름","직업","취미"],                     answer: "이름" },
      { sentence_en: "I am eating bread.",              sentence_kr: "저는 ___을 먹고 있어요.",           blank: "___", options: ["물","사과","빵","우유"],                        answer: "빵" },
      { sentence_en: "Count: one, two, ___, four, five.",sentence_kr: "하나, 둘, ___, 넷, 다섯.",        blank: "___", options: ["셋","여섯","일곱","여덟"],                       answer: "셋" },
      { sentence_en: "The sky is blue.",                sentence_kr: "하늘이 ___에요.",                   blank: "___", options: ["빨간색","파란색","노란색","하얀색"],             answer: "파란색" },
      { sentence_en: "I sit on the chair.",             sentence_kr: "저는 ___에 앉아요.",                blank: "___", options: ["가방","책","의자","집"],                        answer: "의자" },
      { sentence_en: "I drink coffee every morning.",   sentence_kr: "저는 매일 아침 ___를 마셔요.",      blank: "___", options: ["물","주스","커피","우유"],                      answer: "커피" },
      { sentence_en: "The bird is sitting on the tree.",sentence_kr: "나무 위에 ___가 앉아 있어요.",      blank: "___", options: ["개","고양이","새","토끼"],                      answer: "새" },
      { sentence_en: "My favorite color is green.",     sentence_kr: "제가 좋아하는 색은 ___이에요.",     blank: "___", options: ["빨간색","파란색","초록색","노란색"],             answer: "초록색" },
      { sentence_en: "My father goes to work every day.",sentence_kr: "제 ___는 매일 회사에 가요.",       blank: "___", options: ["어머니","아버지","동생","친구"],                 answer: "아버지" },
      { sentence_en: "The dog is barking loudly.",      sentence_kr: "___가 크게 짖어요.",                blank: "___", options: ["고양이","개","새","토끼"],                      answer: "개" },
      { sentence_en: "It is cold outside, so wear a coat.",sentence_kr: "밖이 추우니까 ___를 입어요.",   blank: "___", options: ["신발","모자","코트","양말"],                     answer: "코트" },
      { sentence_en: "Today is Monday.",                sentence_kr: "오늘은 ___이에요.",                 blank: "___", options: ["화요일","월요일","금요일","일요일"],              answer: "월요일" },
      { sentence_en: "I have a headache.",              sentence_kr: "___가 아파요.",                     blank: "___", options: ["눈","코","머리","발"],                          answer: "머리" },
      { sentence_en: "I love eating instant noodles.",  sentence_kr: "저는 ___을 먹는 것을 좋아해요.",   blank: "___", options: ["밥","빵","라면","국"],                          answer: "라면" },
      { sentence_en: "I have a pet cat.",               sentence_kr: "저는 반려 ___를 키워요.",           blank: "___", options: ["개","고양이","새","토끼"],                      answer: "고양이" },
      { sentence_en: "Bananas are yellow.",             sentence_kr: "바나나는 ___이에요.",               blank: "___", options: ["빨간색","파란색","노란색","초록색"],             answer: "노란색" },
      { sentence_en: "I am eight years old.",           sentence_kr: "저는 ___살이에요.",                 blank: "___", options: ["여섯","일곱","여덟","아홉"],                    answer: "여덟" },
      { sentence_en: "Put on shoes before going outside.",sentence_kr: "밖에 나가기 전에 ___을 신어요.", blank: "___", options: ["모자","코트","신발","양말"],                     answer: "신발" },
      { sentence_en: "My grandmother is very healthy.", sentence_kr: "저의 ___는 매우 건강해요.",         blank: "___", options: ["아버지","어머니","동생","할머니"],                answer: "할머니" },
      { sentence_en: "I am a teacher.",                 sentence_kr: "저는 ___이에요.",                   blank: "___", options: ["학생","선생님","친구","사람"],                   answer: "선생님" }
    ],
    intermediate: [
      { sentence_en: "How much is this?",               sentence_kr: "이거 ___?",                         blank: "___", options: ["어디예요?","뭐예요?","얼마예요?","언제예요?"],   answer: "얼마예요?" },
      { sentence_en: "I want to eat bibimbap.",         sentence_kr: "저는 ___을 먹고 싶어요.",           blank: "___", options: ["김치찌개","비빔밥","삼겹살","떡볶이"],         answer: "비빔밥" },
      { sentence_en: "The weather is really nice today.",sentence_kr: "오늘 ___가 정말 좋네요.",          blank: "___", options: ["날씨","시간","기분","장소"],                    answer: "날씨" },
      { sentence_en: "I miss you so much.",             sentence_kr: "정말 ___.",                         blank: "___", options: ["보고 싶어","사랑해요","행복해","화이팅"],      answer: "보고 싶어" },
      { sentence_en: "Please give me one more.",        sentence_kr: "하나 더 ___.",                      blank: "___", options: ["주세요","드세요","가세요","오세요"],            answer: "주세요" },
      { sentence_en: "I need to go to the pharmacy.",   sentence_kr: "___에 가야 해요.",                  blank: "___", options: ["시장","백화점","약국","편의점"],                answer: "약국" },
      { sentence_en: "Where is the restroom?",          sentence_kr: "___이 어디예요?",                   blank: "___", options: ["공항","화장실","호텔","지하철"],               answer: "화장실" },
      { sentence_en: "I am going to the concert tomorrow.",sentence_kr: "내일 ___에 가요.",               blank: "___", options: ["노래","팬","콘서트","아이돌"],                answer: "콘서트" },
      { sentence_en: "I am very tired today.",          sentence_kr: "오늘 너무 ___.",                    blank: "___", options: ["행복하다","슬프다","피곤하다","기쁘다"],       answer: "피곤하다" },
      { sentence_en: "I took the train to Busan.",      sentence_kr: "부산까지 ___를 타고 갔어요.",       blank: "___", options: ["지하철","버스","기차","택시"],                  answer: "기차" },
      { sentence_en: "Korean cold noodles are delicious.",sentence_kr: "한국 ___이 정말 맛있어요.",       blank: "___", options: ["비빔밥","삼겹살","냉면","파전"],               answer: "냉면" },
      { sentence_en: "I forgot my passport!",           sentence_kr: "___을 깜빡했어요!",                 blank: "___", options: ["지갑","여권","표","가방"],                     answer: "여권" },
      { sentence_en: "That performance was really awesome!",sentence_kr: "그 공연 정말 ___이었어!",       blank: "___", options: ["화이팅","오빠","대박","아이돌"],               answer: "대박" },
      { sentence_en: "I need to go to the hospital.",   sentence_kr: "___에 가야 해요.",                  blank: "___", options: ["약국","시장","병원","편의점"],                answer: "병원" },
      { sentence_en: "I am hungry, let us eat.",        sentence_kr: "___, 밥 먹자.",                     blank: "___", options: ["피곤하다","배고프다","슬프다","행복하다"],     answer: "배고프다" },
      { sentence_en: "I am a fan of that idol group.",  sentence_kr: "저는 그 아이돌의 ___이에요.",       blank: "___", options: ["팬","가수","노래","콘서트"],                   answer: "팬" },
      { sentence_en: "Please give me a receipt.",       sentence_kr: "___을 주세요.",                     blank: "___", options: ["카드","영수증","세일","가격"],                 answer: "영수증" },
      { sentence_en: "I want to go hiking this weekend.",sentence_kr: "이번 주말에 ___을 하고 싶어요.",   blank: "___", options: ["수영","독서","등산","게임"],                   answer: "등산" },
      { sentence_en: "The doctor said I have a cold.",  sentence_kr: "의사가 ___에 걸렸다고 했어요.",     blank: "___", options: ["두통","감기","열","주사"],                     answer: "감기" },
      { sentence_en: "Can I get a discount on this?",   sentence_kr: "이거 ___해 주실 수 있어요?",        blank: "___", options: ["교환","환불","할인","세일"],                   answer: "할인" },
      { sentence_en: "I enjoy cooking Korean food.",    sentence_kr: "저는 한국 음식 ___를 좋아해요.",    blank: "___", options: ["여행","독서","운동","요리"],                   answer: "요리" },
      { sentence_en: "I went to the department store.", sentence_kr: "옷을 사러 ___에 갔어요.",           blank: "___", options: ["편의점","백화점","시장","약국"],               answer: "백화점" },
      { sentence_en: "I need to exchange money before my trip.",sentence_kr: "여행 전에 ___을 해야 해요.",blank: "___", options: ["여권","표","환전","호텔"],                   answer: "환전" },
      { sentence_en: "Beautiful flowers bloom in spring.",sentence_kr: "봄에는 예쁜 ___이 피어요.",       blank: "___", options: ["구름","꽃","바람","눈"],                      answer: "꽃" },
      { sentence_en: "The mountain is very tall.",      sentence_kr: "이 ___은 정말 높아요.",             blank: "___", options: ["바다","강","산","하늘"],                      answer: "산" },
      { sentence_en: "I love watching the ocean.",      sentence_kr: "저는 ___을 보는 것을 좋아해요.",   blank: "___", options: ["산","바다","강","하늘"],                      answer: "바다" },
      { sentence_en: "She is a nurse at the hospital.", sentence_kr: "그녀는 병원에서 일하는 ___예요.",   blank: "___", options: ["의사","간호사","약사","요리사"],               answer: "간호사" },
      { sentence_en: "I want to learn how to swim.",    sentence_kr: "___하는 법을 배우고 싶어요.",       blank: "___", options: ["등산","수영","독서","게임"],                   answer: "수영" },
      { sentence_en: "I go dancing every Friday night.",sentence_kr: "매주 금요일 저녁에 ___을 춰요.",   blank: "___", options: ["요리","독서","운동","춤"],                    answer: "춤" },
      { sentence_en: "The singer has released a new album.",sentence_kr: "그 가수가 새 ___을 냈어요.",   blank: "___", options: ["노래","콘서트","앨범","팬덤"],                answer: "앨범" }
    ],
    advanced: [
      { sentence_en: "You really know how to read the room.",           sentence_kr: "당신은 정말 ___가 빠르네요.",            blank: "___", options: ["눈치","정","빨리","마음"],               answer: "눈치" },
      { sentence_en: "Honestly, it was a bit difficult.",               sentence_kr: "___, 조금 어려웠어요.",                  blank: "___", options: ["아무튼","솔직히","그러게요","어쩔 수 없다"], answer: "솔직히" },
      { sentence_en: "Anyway, let us move on.",                         sentence_kr: "___, 계속 진행하죠.",                    blank: "___", options: ["솔직히","설레다","아무튼","귀찮다"],       answer: "아무튼" },
      { sentence_en: "You use a subject particle after the subject.",   sentence_kr: "한국어에서 주어 뒤에 ___ 을 붙여요.",    blank: "___", options: ["조사","존댓말","반말","동사"],          answer: "조사" },
      { sentence_en: "The protagonist of this drama is very cool.",     sentence_kr: "이 드라마의 ___이 정말 멋있어요.",        blank: "___", options: ["주인공","배우","감독","작가"],          answer: "주인공" },
      { sentence_en: "I feel so excited thinking about tomorrow.",      sentence_kr: "내일 생각에 가슴이 ___.",                 blank: "___", options: ["귀찮다","어색하다","설레다","슬프다"],    answer: "설레다" },
      { sentence_en: "This task is such a hassle.",                     sentence_kr: "이 일이 너무 ___.",                       blank: "___", options: ["설레다","고생하다","귀찮다","어색하다"],  answer: "귀찮다" },
      { sentence_en: "There is nothing we can do about it.",            sentence_kr: "___.",                                    blank: "___", options: ["아무튼","그러게요","어쩔 수 없다","솔직히"], answer: "어쩔 수 없다" },
      { sentence_en: "Korean culture values social dignity.",           sentence_kr: "한국 문화에서는 ___을 중요시해요.",       blank: "___", options: ["눈치","정","체면","한"],                answer: "체면" },
      { sentence_en: "Polite speech is used when talking to elders.",   sentence_kr: "어른에게 말할 때는 ___을 사용해요.",      blank: "___", options: ["반말","존댓말","조사","동사"],          answer: "존댓말" },
      { sentence_en: "The concept of han represents deep collective sorrow.",sentence_kr: "한국 문화에서 ___은 깊은 슬픔을 나타내요.", blank: "___", options: ["정","눈치","한","체면"],       answer: "한" },
      { sentence_en: "Thanks to the Korean Wave, K-pop is global.",     sentence_kr: "___ 덕분에 K-pop이 세계적이에요.",        blank: "___", options: ["드라마","한류","아이돌","안무"],        answer: "한류" },
      { sentence_en: "You need courage to try new things.",             sentence_kr: "새로운 것을 시도하려면 ___가 필요해요.",   blank: "___", options: ["지혜","용기","신뢰","겸손"],          answer: "용기" },
      { sentence_en: "Wisdom comes with experience.",                   sentence_kr: "경험에서 ___가 생겨요.",                  blank: "___", options: ["신뢰","용기","지혜","배려"],           answer: "지혜" },
      { sentence_en: "The report deadline is tomorrow.",                sentence_kr: "보고서 ___이 내일이에요.",                blank: "___", options: ["회의","발표","마감","계약"],           answer: "마감" },
      { sentence_en: "Trust is the foundation of a good relationship.", sentence_kr: "좋은 관계의 기본은 ___이에요.",           blank: "___", options: ["배려","지혜","신뢰","용기"],          answer: "신뢰" },
      { sentence_en: "The male lead of that drama is so cool.",         sentence_kr: "그 드라마의 ___가 정말 멋있어요.",        blank: "___", options: ["여주","남주","주인공","배우"],         answer: "남주" },
      { sentence_en: "The atmosphere here is really good.",             sentence_kr: "여기 ___가 정말 좋네요.",                 blank: "___", options: ["눈치","체면","분위기","정"],           answer: "분위기" },
      { sentence_en: "I feel empty after failing the exam.",            sentence_kr: "시험에 떨어지고 나서 ___해요.",           blank: "___", options: ["설레다","억울하다","허탈하다","민망하다"], answer: "허탈하다" },
      { sentence_en: "It was really embarrassing to watch.",            sentence_kr: "그 상황이 정말 ___했어요.",               blank: "___", options: ["억울하다","허탈하다","민망하다","어색하다"], answer: "민망하다" },
      { sentence_en: "I feel wronged because it was not my fault.",     sentence_kr: "제 잘못이 아닌데 정말 ___해요.",          blank: "___", options: ["민망하다","허탈하다","억울하다","어색하다"], answer: "억울하다" },
      { sentence_en: "This solution kills two birds with one stone!",   sentence_kr: "이 방법으로 두 가지를 해결했어요 - ___이에요!", blank: "___", options: ["일석이조","이심전심","작심삼일","고진감래"], answer: "일석이조" },
      { sentence_en: "I need more leisure time in my life.",            sentence_kr: "제 삶에 ___가 필요해요.",                 blank: "___", options: ["분위기","배려","체면","여유"],          answer: "여유" },
      { sentence_en: "My resolution became a three-day affair.",        sentence_kr: "새해 결심이 또 ___가 됐어요.",            blank: "___", options: ["일석이조","이심전심","작심삼일","새옹지마"], answer: "작심삼일" },
      { sentence_en: "Showing consideration for others is a virtue.",   sentence_kr: "다른 사람을 위한 ___는 훌륭한 덕목이에요.",blank: "___", options: ["여유","신뢰","배려","용기"],          answer: "배려" },
      { sentence_en: "I went to Seoul on a business trip.",             sentence_kr: "서울로 ___을 갔어요.",                    blank: "___", options: ["회의","발표","출장","계약"],           answer: "출장" },
      { sentence_en: "The bond with an old friend is very deep.",       sentence_kr: "오랜 친구와의 ___은 정말 깊어요.",        blank: "___", options: ["눈치","체면","정","한"],                answer: "정" },
      { sentence_en: "I felt awkward meeting him after so long.",       sentence_kr: "오랜만에 만나니 좀 ___.",                 blank: "___", options: ["설레다","귀찮다","어색하다","피곤하다"],  answer: "어색하다" },
      { sentence_en: "You worked so hard today, thank you.",            sentence_kr: "오늘 정말 ___.",                         blank: "___", options: ["아무튼","솔직히","고생했어","그러게요"],   answer: "고생했어" },
      { sentence_en: "Informal speech between close friends is called banmal.",sentence_kr: "친한 친구끼리 쓰는 말을 ___이라고 해요.", blank: "___", options: ["존댓말","높임말","반말","조사"],  answer: "반말" }
    ]
  },
  oxQuiz: {
    beginner: [
      { question: "In Korean, 안녕하세요 is used to say hello.",                 answer: true,  explanation: "안녕하세요 (annyeonghaseyo) is the most common formal Korean greeting." },
      { question: "Korean is written from right to left.",                       answer: false, explanation: "Korean (Hangul) is written from left to right, just like English." },
      { question: "감사합니다 means I am sorry in Korean.",                      answer: false, explanation: "감사합니다 means Thank you. 미안합니다 means I am sorry." },
      { question: "The Korean alphabet is called Hangul (한글).",                answer: true,  explanation: "Hangul was created by King Sejong the Great in 1443." },
      { question: "네 means Yes in Korean.",                                      answer: true,  explanation: "네 (ne) means yes. 아니요 (aniyo) means no." },
      { question: "Korea has only one official language.",                        answer: true,  explanation: "Korean is the official language of both North and South Korea." },
      { question: "In Korea, everyone is 1 year old at birth in the traditional age system.", answer: true, explanation: "In traditional Korean age, everyone is 1 at birth and gains a year every New Year." },
      { question: "빵 means rice in Korean.",                                     answer: false, explanation: "빵 means bread. 밥 means rice or a meal." },
      { question: "Hangul has 14 consonants and 10 vowels.",                     answer: true,  explanation: "Hangul totals 24 letters: 14 consonants (자음) and 10 vowels (모음)." },
      { question: "동생 means older sibling in Korean.",                         answer: false, explanation: "동생 means younger sibling. Older siblings: 형, 누나, 오빠, 언니." },
      { question: "The number 다섯 means five in Korean.",                       answer: true,  explanation: "다섯 is the native Korean word for five." },
      { question: "어머니 means father in Korean.",                              answer: false, explanation: "어머니 means mother. 아버지 means father." },
      { question: "친구 means friend in Korean.",                                answer: true,  explanation: "친구 (chingu) is the Korean word for friend." },
      { question: "Korean sentences follow Subject-Verb-Object order like English.", answer: false, explanation: "Korean follows Subject-Object-Verb (SOV) order. The verb comes at the end." },
      { question: "학교 means school in Korean.",                                answer: true,  explanation: "학교 (hakgyo) is the Korean word for school." },
      { question: "Korean is the official language of Japan.",                   answer: false, explanation: "Japanese is the official language of Japan. Korean is spoken in Korea." },
      { question: "Korea is located in East Asia.",                              answer: true,  explanation: "The Korean peninsula is located in East Asia, bordered by China and Japan." },
      { question: "The Korean flag is called the Taegukgi (태극기).",            answer: true,  explanation: "The Taegukgi features a red and blue yin-yang symbol on a white background with black trigrams." },
      { question: "할머니 means grandfather in Korean.",                         answer: false, explanation: "할머니 means grandmother. 할아버지 means grandfather." },
      { question: "Korean numbers can be counted in two different systems.",     answer: true,  explanation: "Korean has Sino-Korean numbers (일, 이, 삼...) and native Korean numbers (하나, 둘, 셋...)." },
      { question: "집 means restaurant in Korean.",                              answer: false, explanation: "집 means house or home. 식당 means restaurant." },
      { question: "개 means cat in Korean.",                                     answer: false, explanation: "개 means dog. 고양이 means cat." },
      { question: "고맙습니다 is another way to say thank you in Korean.",       answer: true,  explanation: "고맙습니다 (formal) and 고마워요 (informal) both mean thank you." },
      { question: "월요일 means Sunday in Korean.",                              answer: false, explanation: "월요일 means Monday. 일요일 means Sunday." },
      { question: "Korea uses the Latin alphabet for writing.",                  answer: false, explanation: "Korea uses Hangul (한글), its own unique alphabet invented in 1443." },
      { question: "The Korean word for teacher is 선생님.",                      answer: true,  explanation: "선생님 (seonsaengnim) means teacher in Korean." },
      { question: "In Korea, it is customary to remove shoes before entering a home.", answer: true, explanation: "Koreans always remove shoes at the entrance (현관) before entering a home." },
      { question: "고양이 means bird in Korean.",                                answer: false, explanation: "고양이 means cat. 새 means bird." },
      { question: "Koreans typically eat with chopsticks and a spoon.",         answer: true,  explanation: "Koreans use metal chopsticks and a spoon (숟가락) together, unlike many other Asian countries." },
      { question: "The word 월요일 (Monday) contains the character for moon (월/月).", answer: true, explanation: "월 (月) means moon. The days of the week in Korean are named after celestial bodies and elements." },
      { question: "토끼 means rabbit in Korean.",                                answer: true,  explanation: "토끼 (tokki) is the Korean word for rabbit." },
      { question: "열 means twenty in Korean native numbers.",                   answer: false, explanation: "열 means ten. 스물 means twenty in native Korean numbers." },
      { question: "Koreans bow as a common form of greeting.",                  answer: true,  explanation: "Bowing is used for greetings, thanks, and apologies in Korean culture." },
      { question: "김치 is always made from cabbage.",                           answer: false, explanation: "There are over 200 types of kimchi made from many vegetables including radish and cucumber." },
      { question: "가방 means chair in Korean.",                                 answer: false, explanation: "가방 means bag. 의자 means chair." },
      { question: "Korean uses spaces between words just like English.",        answer: true,  explanation: "Korean does use spaces between words, though the rules differ from English." },
      { question: "오빠 is used by younger girls to address an older male.",    answer: true,  explanation: "오빠 is used by females to address older brothers or close older male friends." },
      { question: "파란색 refers to the color blue.",                            answer: true,  explanation: "파란색 (paransaek) means blue in Korean." },
      { question: "In Korean, 물 means fire.",                                   answer: false, explanation: "물 means water. 불 means fire." },
      { question: "Korean BBQ is called 삼겹살 when it uses pork belly.",        answer: true,  explanation: "삼겹살 literally means three-layer flesh, referring to pork belly." }
    ],
    intermediate: [
      { question: "Kimchi is always spicy.",                                     answer: false, explanation: "There are over 200 types of kimchi. White kimchi (백김치) is not spicy at all." },
      { question: "In Korea, it is polite to receive things with two hands.",   answer: true,  explanation: "Using two hands or one hand supported by the other arm shows respect." },
      { question: "대박 is used to say awesome or jackpot.",                    answer: true,  explanation: "대박 originally meant a big hit or jackpot, now used to express amazement." },
      { question: "Korean BBQ is always eaten indoors.",                        answer: false, explanation: "Korean BBQ can be enjoyed both indoors and outdoors." },
      { question: "Seoul is the capital city of South Korea.",                  answer: true,  explanation: "Seoul (서울) has been the capital for over 600 years." },
      { question: "The Korean subway system is the largest in the world.",      answer: false, explanation: "Seoul's subway is one of the largest, but Beijing and Shanghai's are larger by network size." },
      { question: "Chuseok is a major Korean harvest festival similar to Thanksgiving.", answer: true, explanation: "Chuseok (추석) is celebrated on the 15th day of the 8th lunar month." },
      { question: "화이팅 is a Korean cheer borrowed from the English word fighting.", answer: true, explanation: "화이팅 or 파이팅 is used to cheer someone on, adapted from the English word." },
      { question: "Bulgogi is a type of cold Korean noodle dish.",              answer: false, explanation: "Bulgogi (불고기) is marinated grilled beef. Cold noodles are called 냉면." },
      { question: "Tteokbokki is traditionally a sweet dish.",                 answer: false, explanation: "Tteokbokki (떡볶이) is traditionally spicy, made with gochujang (red pepper paste)." },
      { question: "In Korea, slurping noodles is considered rude.",             answer: false, explanation: "Slurping noodles is acceptable in Korea and can signal enjoyment of the food." },
      { question: "편의점 means convenience store in Korean.",                   answer: true,  explanation: "편의점 (pyeonuijeom) means convenience store. GS25 and CU are popular chains." },
      { question: "Samgyeopsal is a type of beef dish.",                        answer: false, explanation: "Samgyeopsal (삼겹살) is grilled pork belly, not beef. Beef dishes include bulgogi and galbi." },
      { question: "보고 싶어 is a casual way to say I miss you.",               answer: true,  explanation: "보고 싶어 literally means I want to see you and is used to express missing someone." },
      { question: "Japchae is made with glass noodles called 당면.",            answer: true,  explanation: "Japchae (잡채) features sweet potato glass noodles stir-fried with vegetables and meat." },
      { question: "Samgyetang is traditionally eaten only in winter.",          answer: false, explanation: "Samgyetang (삼계탕) is actually most popular in summer to combat the heat, especially on Sambok days." },
      { question: "Korea has four distinct seasons.",                            answer: true,  explanation: "Korea experiences spring, summer, autumn, and winter, each with distinct characteristics." },
      { question: "갈비 refers to ribs in Korean cooking.",                     answer: true,  explanation: "갈비 means ribs. Popular dishes include 갈비탕 (rib soup) and 갈비구이 (grilled ribs)." },
      { question: "약사 means nurse in Korean.",                                 answer: false, explanation: "약사 means pharmacist. 간호사 means nurse." },
      { question: "In Korean culture, pouring your own drink is considered impolite.", answer: true, explanation: "It is polite to pour drinks for others while they pour for you." },
      { question: "Korean convenience stores are open 24 hours a day.",         answer: true,  explanation: "Most Korean convenience stores (편의점) operate 24/7, 365 days a year." },
      { question: "독서 means exercise in Korean.",                              answer: false, explanation: "독서 means reading. 운동 means exercise or sports." },
      { question: "The Han River (한강) flows through Seoul.",                  answer: true,  explanation: "The Han River divides Seoul into northern (강북) and southern (강남) areas." },
      { question: "K-pop has gained worldwide popularity since the 2000s.",     answer: true,  explanation: "K-pop began gaining international attention in Asia in the late 1990s and globally in the 2010s." },
      { question: "In Korea, writing someone's name in red ink is considered lucky.", answer: false, explanation: "Writing a name in red ink is associated with death in Korean culture and should be avoided." },
      { question: "날씨 refers specifically to temperature.",                   answer: false, explanation: "날씨 means weather in general. 온도 means temperature specifically." },
      { question: "BTS is a Korean idol group.",                                 answer: true,  explanation: "BTS (방탄소년단) is a globally famous South Korean boy band formed in 2013." },
      { question: "건강 means sickness in Korean.",                              answer: false, explanation: "건강 means health. 병 or 아픔 means sickness." },
      { question: "Traditional Korean clothing is called Hanbok (한복).",       answer: true,  explanation: "Hanbok has been worn for thousands of years and is still worn on special occasions." },
      { question: "The Korean won (원) is the currency of South Korea.",        answer: true,  explanation: "The South Korean won (KRW) has been the official currency since 1962." },
      { question: "등산 means swimming in Korean.",                              answer: false, explanation: "등산 means hiking. 수영 means swimming." },
      { question: "Tteokguk is traditionally eaten on New Year's Day in Korea.",answer: true,  explanation: "Eating tteokguk (떡국) on Seollal (Korean New Year) symbolizes gaining a year of age." },
      { question: "구름 means sun in Korean.",                                   answer: false, explanation: "구름 means cloud. 태양 means sun." },
      { question: "Korean fans give their idols light sticks at concerts.",     answer: true,  explanation: "Each K-pop group has its own official light stick used by fans at concerts." },
      { question: "In Korea, younger people use formal speech to elders.",      answer: true,  explanation: "Korean has a complex speech level system based on age and social relationship." },
      { question: "할인 means full price in Korean.",                            answer: false, explanation: "할인 means discount. 정가 means full or regular price." },
      { question: "Korea was divided into North and South after World War II.",  answer: true,  explanation: "Korea was divided along the 38th parallel after Japan's defeat in 1945." },
      { question: "기차 means airplane in Korean.",                              answer: false, explanation: "기차 means train. 비행기 means airplane." },
      { question: "Doenjang is a type of fermented soybean paste.",             answer: true,  explanation: "Doenjang (된장) is a traditional Korean condiment made from fermented soybeans." },
      { question: "요리사 means waiter in Korean.",                              answer: false, explanation: "요리사 means chef or cook. 웨이터 means waiter." }
    ],
    advanced: [
      { question: "In Korean grammar, the verb always comes at the end of the sentence.", answer: true, explanation: "Korean follows Subject-Object-Verb (SOV) order, unlike English SVO." },
      { question: "존댓말 and 반말 refer to different levels of formality in Korean.", answer: true, explanation: "존댓말 is polite/formal speech, 반말 is casual speech used between close friends or to juniors." },
      { question: "The particle 은/는 marks the object of a sentence.",         answer: false, explanation: "은/는 is the topic particle. 을/를 marks the object of a sentence." },
      { question: "눈치 is a uniquely Korean concept with no direct English translation.", answer: true, explanation: "눈치 describes reading a social situation without being explicitly told — a valued social skill." },
      { question: "Korean has exactly 24 letters in the Hangul alphabet.",      answer: true,  explanation: "Hangul has 14 consonants (자음) and 10 vowels (모음) = 24 letters total." },
      { question: "In Korean, age determines the speech level you use.",        answer: true,  explanation: "Younger people use formal speech to elders; same-age friends can use casual speech." },
      { question: "빨리빨리 culture refers to Koreans preference for slowness.", answer: false, explanation: "빨리빨리 means hurry hurry — it refers to Korea's well-known preference for speed and efficiency." },
      { question: "정 (jeong) refers to a romantic feeling only.",              answer: false, explanation: "정 is a deep emotional bond that can exist between family, friends, or anyone you feel connected to." },
      { question: "The subject particles in Korean are 이 and 가.",             answer: true,  explanation: "이 is used after consonants, 가 after vowels. Both mark the subject of a sentence." },
      { question: "한 is a uniquely Korean feeling of deep sorrow and resentment.", answer: true, explanation: "한 (恨) expresses collective grief and sorrow deeply rooted in Korean historical experience." },
      { question: "남주 and 여주 are terms for the male and female leads in a drama.", answer: true, explanation: "남주 (남자 주인공) = male lead, 여주 (여자 주인공) = female lead. Common in Korean fan culture." },
      { question: "Using banmal (반말) with a stranger in Korea is polite.",     answer: false, explanation: "Using banmal with a stranger or elder is rude. Always default to 존댓말 with people you just met." },
      { question: "체면 refers to the concept of social face or dignity.",      answer: true,  explanation: "체면 is the social pressure to maintain one's dignity and reputation in front of others." },
      { question: "Korean verbs change based on the social relationship between speakers.", answer: true, explanation: "Korean has multiple speech levels that change verb endings based on social context and relationship." },
      { question: "갑 always refers to the person with less power.",            answer: false, explanation: "갑 refers to the more powerful party (Party A). 을 is the less powerful party (Party B)." },
      { question: "눈치 is considered a positive social skill in Korea.",       answer: true,  explanation: "Being good at 눈치 (눈치가 빠르다) means you read the room well, which is highly valued socially." },
      { question: "Korean sentences must always end with a verb or adjective.", answer: true,  explanation: "Predicates (verbs and adjectives) always come at the end in Korean sentences." },
      { question: "이심전심 literally means heart to heart.",                   answer: true,  explanation: "以心傳心 (이심전심) means transmitting from heart to heart — a kind of mutual understanding without words." },
      { question: "In Korean, adjectives conjugate just like verbs.",           answer: true,  explanation: "Korean adjectives take verbal endings and conjugate for tense, formality, and mood." },
      { question: "갑을관계 refers to power dynamics between two parties.",     answer: true,  explanation: "갑을관계 describes the hierarchical relationship between a powerful party (갑) and a weaker one (을)." },
      { question: "Korean grammar has absolutely no passive voice constructions.", answer: false, explanation: "Korean has passive constructions formed using suffixes like -이-, -히-, -리-, -기- and -아/어지다." },
      { question: "새옹지마 is a Chinese proverb adapted into Korean.",          answer: true,  explanation: "새옹지마 comes from the Chinese story of an old man whose horse ran away — a tale about life's uncertainty." },
      { question: "작심삼일 means being committed to a resolution for a long time.", answer: false, explanation: "작심삼일 (作心三日) means a resolution that lasts only three days — giving up quickly after starting." },
      { question: "Korean has more than 5 distinct speech levels.",             answer: true,  explanation: "Korean has six speech levels (격식체/비격식체), though modern use typically focuses on two or three." },
      { question: "K-dramas spread Korean culture in Asia before K-pop became dominant.", answer: true, explanation: "K-dramas like 겨울연가 sparked the Korean Wave in Asia in the early 2000s, preceding the K-pop explosion." },
      { question: "The object particle in Korean is 이/가.",                    answer: false, explanation: "이/가 is the subject particle. 을/를 is the object particle in Korean." },
      { question: "배려 and 눈치 are related but distinct Korean cultural concepts.", answer: true, explanation: "배려 means showing consideration for others proactively; 눈치 means reading the social situation reactively." },
      { question: "Korean has honorific vocabulary that completely replaces regular words.", answer: true, explanation: "For example: 먹다→드시다 (eat), 있다→계시다 (to be/stay), 집→댁 (home). Fully different words." },
      { question: "고진감래 means the harder you work, the worse things get.",  answer: false, explanation: "고진감래 (苦盡甘來) means after bitterness comes sweetness — after hardship comes happiness." },
      { question: "Using -님 after a title makes it more respectful in Korean.", answer: true,  explanation: "선생님, 사장님, 고객님 — adding 님 shows respect toward the person being addressed." },
      { question: "Korean Internet slang uses symbols like ㅋㅋ for laughing.", answer: true,  explanation: "ㅋㅋ represents laughter (from 크크 or 킥킥), ㅠㅠ represents crying with tear-drop eyes." },
      { question: "뿌듯하다 describes feeling proud only about others achievements.", answer: false, explanation: "뿌듯하다 describes a warm feeling of satisfaction or pride, which can be about yourself or others." },
      { question: "일석이조 has an English equivalent: killing two birds with one stone.", answer: true, explanation: "일석이조 (一石二鳥) and kill two birds with one stone convey the same idea across cultures." },
      { question: "Hangul was invented during the Goryeo Dynasty.",              answer: false, explanation: "Hangul was created by King Sejong the Great during the Joseon Dynasty (1443 AD), not Goryeo." },
      { question: "In Korean, 밥 먹었어? (Did you eat?) can function as a casual greeting.", answer: true, explanation: "Asking if someone ate is a common Korean expression of care and concern, often used as a greeting." },
      { question: "고생했어 is appropriate to say after someone completes hard work.", answer: true, explanation: "고생했어 acknowledges someone's effort and says you recognize how hard they worked." },
      { question: "서운하다 means feeling physically cold in Korean.",           answer: false, explanation: "서운하다 means feeling emotionally hurt or let down by someone close to you. 춥다 means cold." },
      { question: "The Korean concept of 흥 describes a spontaneous joy and excitement.", answer: true, explanation: "흥 is a uniquely Korean concept of rhythmic excitement and communal joy, often associated with music and dance." },
      { question: "눈치채다 means to sense or pick up on something without being told.", answer: true, explanation: "눈치채다 means to detect or sense something — like realizing someone is upset without them saying so." },
      { question: "오매불망 means completely forgetting about someone.",         answer: false, explanation: "오매불망 means to think about someone constantly day and night — the opposite of forgetting." }
    ]
  },
  sentencePuzzle: {
    beginner: [
      { words: ["저는","학생","이에요"],                   correct_order: [0,1,2],     translation: "I am a student." },
      { words: ["물","주세요"],                             correct_order: [0,1],       translation: "Please give me water." },
      { words: ["이름이","뭐예요?"],                        correct_order: [0,1],       translation: "What is your name?" },
      { words: ["저는","밥을","먹어요"],                  correct_order: [0,1,2],     translation: "I eat rice." },
      { words: ["오늘","날씨가","좋아요"],                correct_order: [0,1,2],     translation: "The weather is nice today." },
      { words: ["저는","사과를","좋아해요"],              correct_order: [0,1,2],     translation: "I like apples." },
      { words: ["친구가","학교에","가요"],                correct_order: [0,1,2],     translation: "My friend goes to school." },
      { words: ["이","가방은","제","거예요"],           correct_order: [0,1,2,3],   translation: "This bag is mine." },
      { words: ["어머니가","밥을","만들어요"],            correct_order: [0,1,2],     translation: "My mother makes rice." },
      { words: ["지금","몇","시예요?"],                   correct_order: [0,1,2],     translation: "What time is it now?" },
      { words: ["저는","한국어를","공부해요"],            correct_order: [0,1,2],     translation: "I study Korean." },
      { words: ["이","책은","재미있어요"],                correct_order: [0,1,2],     translation: "This book is interesting." },
      { words: ["커피를","마셔요"],                         correct_order: [0,1],       translation: "I drink coffee." },
      { words: ["개가","짖어요"],                           correct_order: [0,1],       translation: "The dog barks." },
      { words: ["오늘은","화요일이에요"],                   correct_order: [0,1],       translation: "Today is Tuesday." },
      { words: ["어머니가","요리를","해요"],              correct_order: [0,1,2],     translation: "Mother is cooking." },
      { words: ["제","신발이","빨간색이에요"],            correct_order: [0,1,2],     translation: "My shoes are red." },
      { words: ["저는","라면을","좋아해요"],              correct_order: [0,1,2],     translation: "I like ramen." },
      { words: ["지금","몇","살이에요?"],                 correct_order: [0,1,2],     translation: "How old are you?" },
      { words: ["고양이가","자고","있어요"],              correct_order: [0,1,2],     translation: "The cat is sleeping." },
      { words: ["우리는","친구예요"],                       correct_order: [0,1],       translation: "We are friends." },
      { words: ["아버지는","회사에","가요"],              correct_order: [0,1,2],     translation: "Father goes to work." },
      { words: ["제","가방이","파란색이에요"],            correct_order: [0,1,2],     translation: "My bag is blue." },
      { words: ["양말이","어디에","있어요?"],             correct_order: [0,1,2],     translation: "Where are the socks?" },
      { words: ["주스를","마시고","싶어요"],              correct_order: [0,1,2],     translation: "I want to drink juice." }
    ],
    intermediate: [
      { words: ["비빔밥","하나","주세요"],                correct_order: [0,1,2],     translation: "Please give me one bibimbap." },
      { words: ["지하철역이","어디예요?"],                  correct_order: [0,1],       translation: "Where is the subway station?" },
      { words: ["저는","한국어를","배우고","있어요"],   correct_order: [0,1,2,3],   translation: "I am learning Korean." },
      { words: ["오빠를","보고","싶어요"],               correct_order: [0,1,2],     translation: "I miss you, oppa." },
      { words: ["이거","얼마예요?"],                        correct_order: [0,1],       translation: "How much is this?" },
      { words: ["날씨가","너무","더워요"],               correct_order: [0,1,2],     translation: "The weather is too hot." },
      { words: ["공항까지","어떻게","가요?"],            correct_order: [0,1,2],     translation: "How do I get to the airport?" },
      { words: ["삼겹살이","정말","맛있어요"],           correct_order: [0,1,2],     translation: "Samgyeopsal is really delicious." },
      { words: ["저는","지금","많이","피곤해요"],      correct_order: [0,1,2,3],   translation: "I am very tired right now." },
      { words: ["콘서트","표를","샀어요"],               correct_order: [0,1,2],     translation: "I bought a concert ticket." },
      { words: ["화장실이","어디에","있어요?"],           correct_order: [0,1,2],     translation: "Where is the restroom?" },
      { words: ["한국","음식이","정말","좋아요"],      correct_order: [0,1,2,3],   translation: "I really like Korean food." },
      { words: ["저는","의사가","되고","싶어요"],      correct_order: [0,1,2,3],   translation: "I want to become a doctor." },
      { words: ["내일","쇼핑하러","가요"],               correct_order: [0,1,2],     translation: "I am going shopping tomorrow." },
      { words: ["이","옷","사이즈가","맞나요?"],       correct_order: [0,1,2,3],   translation: "Does this clothes size fit?" },
      { words: ["감기에","걸려서","약을","먹었어요"],  correct_order: [0,1,2,3],   translation: "I caught a cold so I took medicine." },
      { words: ["주말에","등산을","해요"],               correct_order: [0,1,2],     translation: "I go hiking on weekends." },
      { words: ["그","아이돌의","팬이에요"],             correct_order: [0,1,2],     translation: "I am that idol group's fan." },
      { words: ["이","가격이","너무","비싸요"],        correct_order: [0,1,2,3],   translation: "This price is too expensive." },
      { words: ["저는","독서를","좋아해요"],             correct_order: [0,1,2],     translation: "I like reading." },
      { words: ["환불","받을","수","있어요?"],         correct_order: [0,1,2,3],   translation: "Can I get a refund?" },
      { words: ["이번","주말에","비가","와요"],        correct_order: [0,1,2,3],   translation: "It will rain this weekend." },
      { words: ["저는","회사원이에요"],                     correct_order: [0,1],       translation: "I am an office worker." },
      { words: ["수영장이","어디에","있어요?"],           correct_order: [0,1,2],     translation: "Where is the swimming pool?" },
      { words: ["된장찌개를","끓이고","있어요"],         correct_order: [0,1,2],     translation: "I am making doenjang stew." }
    ],
    advanced: [
      { words: ["그","드라마의","주인공이","정말","멋있어요"],       correct_order: [0,1,2,3,4],   translation: "The main character of that drama is really cool." },
      { words: ["솔직히","말하면","조금","어려웠어요"],               correct_order: [0,1,2,3],     translation: "To be honest, it was a bit difficult." },
      { words: ["한국어는","동사가","문장","끝에","와요"],          correct_order: [0,1,2,3,4],   translation: "In Korean, the verb comes at the end of the sentence." },
      { words: ["당신의","눈치가","정말","빠르네요"],                 correct_order: [0,1,2,3],     translation: "You really read the room well." },
      { words: ["아무튼","계속","열심히","해봐요"],                   correct_order: [0,1,2,3],     translation: "Anyway, let us keep working hard." },
      { words: ["이","일은","어쩔","수","없어요"],                  correct_order: [0,1,2,3,4],   translation: "There is nothing we can do about this." },
      { words: ["존댓말을","사용하는","것이","중요해요"],             correct_order: [0,1,2,3],     translation: "Using polite speech is important." },
      { words: ["눈치가","없으면","실수를","많이","해요"],          correct_order: [0,1,2,3,4],   translation: "If you lack social awareness, you make many mistakes." },
      { words: ["한국어","문법에서","조사가","매우","중요해요"],    correct_order: [0,1,2,3,4],   translation: "Particles are very important in Korean grammar." },
      { words: ["오랜","친구와의","정은","특별해요"],                 correct_order: [0,1,2,3],     translation: "The bond with an old friend is special." },
      { words: ["체면","때문에","솔직하게","말","못","해요"],     correct_order: [0,1,2,3,4,5], translation: "Because of social dignity, I cannot speak honestly." },
      { words: ["내일","시험이라서","설레고","긴장돼요"],             correct_order: [0,1,2,3],     translation: "I am excited and nervous because of tomorrow's exam." },
      { words: ["이","상황이","정말","귀찮아요"],                     correct_order: [0,1,2,3],     translation: "This situation is really annoying." },
      { words: ["세종대왕이","한글을","창제했어요"],                    correct_order: [0,1,2],       translation: "King Sejong created Hangul." },
      { words: ["신뢰와","배려가","좋은","관계의","기본이에요"],   correct_order: [0,1,2,3,4],   translation: "Trust and consideration are the basics of a good relationship." },
      { words: ["한류","덕분에","한국어를","배우는","사람이","많아요"], correct_order: [0,1,2,3,4,5], translation: "Thanks to the Korean Wave, many people learn Korean." },
      { words: ["이","드라마의","남주가","정말","멋있어요"],        correct_order: [0,1,2,3,4],   translation: "The male lead of this drama is really cool." },
      { words: ["회의에서","중요한","계약을","했어요"],               correct_order: [0,1,2,3],     translation: "We signed an important contract at the meeting." },
      { words: ["억울한","상황에서","용기를","냈어요"],               correct_order: [0,1,2,3],     translation: "I gathered courage in an unfair situation." },
      { words: ["그의","뿌듯한","표정을","보니","기뻤어요"],       correct_order: [0,1,2,3,4],   translation: "Seeing his satisfied expression made me happy." },
      { words: ["한국어에서","은/는은","주제","조사예요"],            correct_order: [0,1,2,3],     translation: "In Korean, 은/는 is the topic particle." },
      { words: ["작심삼일이","되지","않으려면","꾸준해야","해요"],  correct_order: [0,1,2,3,4],   translation: "To avoid giving up after three days, you must be consistent." },
      { words: ["한복을","입고","한옥에서","사진을","찍었어요"],    correct_order: [0,1,2,3,4],   translation: "I wore hanbok and took photos at a hanok." },
      { words: ["서운한","마음을","솔직하게","표현했어요"],           correct_order: [0,1,2,3],     translation: "I honestly expressed my hurt feelings." },
      { words: ["눈치를","잘","보면","사회생활이","쉬워요"],       correct_order: [0,1,2,3,4],   translation: "If you read the room well, social life becomes easier." }
    ]
  }

};
